// Extract the MIT KEMAR horizontal-plane HRIRs into a compact data module
// — the owner's route 2 (07-07): the MEASURED impulse responses, so the
// convolution ear model can be A/B'd against the parametric replica.
//
// Only the horizontal plane (elevation 0) is taken, because the engine's
// space model is azimuth-only — 72 azimuths × both ears. KEMAR wore two
// different pinnae (normal DB-061 left, large red DB-065 right), so the
// left/right responses are genuinely different and both are kept.
//
// Dataset: MIT KEMAR (Gardner & Martin 1994, MIT Media Lab TR #280),
// "provided free with no restrictions on use, provided the authors are
// cited". sound.media.mit.edu/resources/KEMAR.html
//
// The raw dataset never enters the repo; this script emits
// web/static/kemar-hrir.js (int16 IRs, base64) — a derived asset the
// owner explicitly asked to bundle so measured and modelled can be
// compared by ear.
//
// Usage: node scripts/extract_kemar_hrir.mjs /path/to/kemar_full

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.argv[2];
if (!root) { console.error("usage: node scripts/extract_kemar_hrir.mjs /path/to/kemar_full"); process.exit(1); }

const TAPS = 256; // 5.8 ms @ 44.1 kHz — the whole direct HRIR incl. onset delay + pinna detail

function readWavInt16(path) {
  const b = readFileSync(path);
  if (b.toString("ascii", 0, 4) !== "RIFF") throw new Error(`not RIFF: ${path}`);
  let off = 12;
  while (off < b.length) {
    const id = b.toString("ascii", off, off + 4);
    const size = b.readUInt32LE(off + 4);
    if (id === "data") {
      const n = Math.min(TAPS, size / 2);
      const out = new Int16Array(TAPS); // zero-padded if shorter
      for (let i = 0; i < n; i++) out[i] = b.readInt16LE(off + 8 + i * 2);
      return out;
    }
    off += 8 + size;
  }
  throw new Error(`no data chunk: ${path}`);
}

const AZ = [];
for (let a = 0; a < 360; a += 5) AZ.push(a);

// Read every azimuth's L and R IR (KEMAR azimuth is clockwise from front,
// which matches our own 0=front,+90=right convention directly).
const irs = AZ.map(a => ({
  L: readWavInt16(join(root, "elev0", `L0e${String(a).padStart(3, "0")}a.wav`)),
  R: readWavInt16(join(root, "elev0", `R0e${String(a).padStart(3, "0")}a.wav`)),
}));

// Level-match to the parametric path (~unity broadband): normalise so the
// FRONT response has unit energy gain. This preserves every inter-azimuth
// and inter-ear difference (the point of the comparison) while making the
// two ear models the same loudness, so an A/B compares colour, not gain.
const energy = (h) => { let s = 0; for (const v of h) s += (v / 32768) ** 2; return s; };
const refE = (energy(irs[0].L) + energy(irs[0].R)) / 2;
const normGain = 1 / Math.sqrt(refE);

// Pack [az0_L, az0_R, az1_L, az1_R, …] little-endian int16 → base64.
const total = irs.length * 2 * TAPS;
const packed = new Int16Array(total);
let w = 0;
for (const ir of irs) { packed.set(ir.L, w); w += TAPS; packed.set(ir.R, w); w += TAPS; }
const b64 = Buffer.from(packed.buffer).toString("base64");

const out = `// GENERATED by scripts/extract_kemar_hrir.mjs — DO NOT EDIT BY HAND.
// Measured horizontal-plane HRIRs of the MIT KEMAR dummy head
// (Gardner & Martin 1994, MIT Media Lab TR #280; free with attribution:
// sound.media.mit.edu/resources/KEMAR.html). Left pinna = normal DB-061,
// right pinna = large DB-065. Owner 07-07 route 2: bundled so the
// convolution ear model can be compared by ear against the parametric fit.
//
// Layout: base64 → little-endian Int16Array, interleaved per azimuth as
// [L(${TAPS}), R(${TAPS})] for azimuths 0,5,…,355 (clockwise from front,
// matching our 0=front/+90=right convention). Normalised to unit front
// energy so it level-matches the parametric path.

export const KEMAR_HRIR = {
  sampleRate: 44100,
  taps: ${TAPS},
  step: 5,          // azimuth resolution, degrees
  count: ${irs.length},
  normGain: ${normGain.toFixed(6)},
  cite: "MIT KEMAR — Gardner & Martin 1994",
  _b64: "${b64}",
};

let _decoded = null; // Int16Array, lazily (keeps Node importers cheap)
function _samples() {
  if (_decoded) return _decoded;
  const bin = typeof atob === "function"
    ? atob(KEMAR_HRIR._b64)
    : Buffer.from(KEMAR_HRIR._b64, "base64").toString("binary");
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  _decoded = new Int16Array(bytes.buffer);
  return _decoded;
}

// The measured left+right impulse responses for a source at ourAzimuthDeg
// (0=front, +90=right, ±180=behind), nearest measured azimuth. Returns
// two mono AudioBuffers, gain-normalised, ready for per-ear convolvers.
// Resampled to the context rate: a ConvolverNode buffer MUST match the
// AudioContext sample rate (KEMAR is 44.1 kHz; many contexts run 48 kHz).
export function kemarBuffers(ctx, ourAzimuthDeg) {
  const s = _samples();
  const { taps, step, count, normGain, sampleRate } = KEMAR_HRIR;
  const az = ((Math.round(ourAzimuthDeg / step) * step) % 360 + 360) % 360;
  const idx = (az / step) % count;
  const base = idx * 2 * taps;
  const ratio = ctx.sampleRate / sampleRate;          // e.g. 48000/44100
  const dstLen = Math.max(1, Math.round(taps * ratio));
  const mk = (off) => {
    const buf = ctx.createBuffer(1, dstLen, ctx.sampleRate);
    const d = buf.getChannelData(0);
    for (let i = 0; i < dstLen; i++) {
      const sp = i / ratio, i0 = Math.floor(sp), frac = sp - i0;
      const a = i0 < taps ? s[base + off + i0] / 32768 : 0;
      const b = i0 + 1 < taps ? s[base + off + i0 + 1] / 32768 : 0;
      d[i] = (a + (b - a) * frac) * normGain;            // linear resample
    }
    return buf;
  };
  return { left: mk(0), right: mk(taps), azimuth: az };
}
`;
writeFileSync(join(process.cwd(), "web/static/kemar-hrir.js"), out);
console.log(`wrote web/static/kemar-hrir.js — ${irs.length} azimuths × 2 ears × ${TAPS} taps, ` +
  `normGain ${normGain.toFixed(4)}, ${(b64.length / 1024).toFixed(0)} KB base64`);
